version: "3"
services:
  ffv:
    build: ./docker
    container_name: ffv
    volumes:
    - ./output:/output
    command: ./build.sh
    environment:
    - GLUON_REPO=https://github.com/freifunk-gluon/gluon.git
    - GLUON_TAG=fastd-l2tp
    - GLUON_DEPRECATED=full
    - TARGETS=rockchip-armv8
    - AUTOUPDATER_ENABLED=false
#    - DEVICES=friendlyelec-nanopi-r2s